<a href="https://colab.research.google.com/github/LokeshPatil-loki/alumnit/blob/master/recommendation-model/alumni_recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import ast

In [2]:
# Mount your google drive in google colab
# from google.colab import drive
# drive.mount('/content/drive')

In [3]:
# dataset = pd.read_csv('/content/drive/MyDrive/Copy of AlumniProfiles.csv')
dataset = pd.read_csv("https://raw.githubusercontent.com/LokeshPatil-loki/alumni-recommendation-data-scrapper/master/Dataset/CSV/AlumniProfiles.csv")

In [4]:
# from google.colab import drive
# drive.mount('/content/drive')

In [5]:
# class Department(Enum):
#   Computer = ("computer","Computer Engineering"),
#   Infomation_Technology = ("infromation","Information Technology")
#   Mechanical = ("mechanical","Mechanical Engineering"),
#   Instrumentation = ()


Departments = {
    "computer": "Computer Engineering",
    "information": "Information Technology",
    "mechanical": "Mechanical Engineering",
    "instrumentation": "Instrumentation",
    "electronic": "Electronic and Telecommunication",
    "chemical": "Chemical Engineering"
}

for x  in Departments.keys():
  print(x)

computer
information
mechanical
instrumentation
electronic
chemical


# **Preporcessing**

In [6]:
dataset.head(5) #drop isAlumni, isConnected,location,messageUrl,url

_id  \
0  63f1e38f0666421fed18d20a   
1  63f1e38f0666421fed18d212   
2  63f1e38f0666421fed18d216   
3  63f1e38f0666421fed18d222   
4  63f1e38f0666421fed18d22a   

                                      certifications  \
0                           [{"title":"","from":""}]   
1                           [{"title":"","from":""}]   
2  [{"title":"Web Development","from":"Verzeo"},{...   
3                           [{"title":"","from":""}]   
4                           [{"title":"","from":""}]   

                                           education  \
0  [{"title":"Bharati Vidyapeeth College of Engin...   
1  [{"title":"Bharati Vidyapeeth College of Engin...   
2  [{"title":"Bharati Vidyapeeth College of Engin...   
3  [{"title":"Bharati Vidyapeeth College of Engin...   
4  [{"title":"Bharati Vidyapeeth College of Engin...   

                                          experinces              fullName  \
0                                                 []  Pralayika Mandapalli   
1  [{"organization":"Reliance Jio Infocom Limited...       Anshu kumar Jha   
2  [{"organization":"Verzeo · Internship","title"...       Vighnesh Jadhav   
3                                                 []         Siddhi Chavan   
4                                                 []           Snehal Kale   

   isAlumni  isConnected                         location  \
0      True         True        Thane, Maharashtra, India   
1      True         True       Mumbai, Maharashtra, India   
2      True         True       Mumbai, Maharashtra, India   
3      True         True       Mumbai, Maharashtra, India   
4      True         True  Navi Mumbai, Maharashtra, India   

                                          messageUrl  \
0  https://www.linkedin.comhttps://www.linkedin.c...   
1  https://www.linkedin.comhttps://www.linkedin.c...   
2  https://www.linkedin.comhttps://www.linkedin.c...   
3  https://www.linkedin.comhttps://www.linkedin.c...   
4  https://www.linkedin.com/messaging/thread/new?...   

                                              skills  \
0                                                 []   
1  ["Java","C (Programming Language)","English","...   
2  ["HTML","Cascading Style Sheets (CSS)","Python...   
3  ["Hindi","Cascading Style Sheets (CSS)","HTML5...   
4                                                 []   

                                               title  \
0  Student at Bharati Vidyapeeth College of Engin...   
1                   Graduate engineer Trainee at Jio   
2                   Assistant System Engineer at TCS   
3  Student at Bharti Vidyapeeth college of engine...   
4   Assistant Manager(GET) at Reliance jio platforms   

                                                 url  
0  https://www.linkedin.com/in/pralayika-mandapal...  
1  https://www.linkedin.com/in/anshu-kumar-jha-3b...  
2  https://www.linkedin.com/in/vighnesh-jadhav-57...  
3  https://www.linkedin.com/in/siddhi-chavan-9908...  
4  https://www.linkedin.com/in/snehal-kale-99026720a

In [7]:
data = dataset.drop(['isAlumni', 'isConnected','location','messageUrl','url'], axis=1)

In [8]:
data.head(5)

_id  \
0  63f1e38f0666421fed18d20a   
1  63f1e38f0666421fed18d212   
2  63f1e38f0666421fed18d216   
3  63f1e38f0666421fed18d222   
4  63f1e38f0666421fed18d22a   

                                      certifications  \
0                           [{"title":"","from":""}]   
1                           [{"title":"","from":""}]   
2  [{"title":"Web Development","from":"Verzeo"},{...   
3                           [{"title":"","from":""}]   
4                           [{"title":"","from":""}]   

                                           education  \
0  [{"title":"Bharati Vidyapeeth College of Engin...   
1  [{"title":"Bharati Vidyapeeth College of Engin...   
2  [{"title":"Bharati Vidyapeeth College of Engin...   
3  [{"title":"Bharati Vidyapeeth College of Engin...   
4  [{"title":"Bharati Vidyapeeth College of Engin...   

                                          experinces              fullName  \
0                                                 []  Pralayika Mandapalli   
1  [{"organization":"Reliance Jio Infocom Limited...       Anshu kumar Jha   
2  [{"organization":"Verzeo · Internship","title"...       Vighnesh Jadhav   
3                                                 []         Siddhi Chavan   
4                                                 []           Snehal Kale   

                                              skills  \
0                                                 []   
1  ["Java","C (Programming Language)","English","...   
2  ["HTML","Cascading Style Sheets (CSS)","Python...   
3  ["Hindi","Cascading Style Sheets (CSS)","HTML5...   
4                                                 []   

                                               title  
0  Student at Bharati Vidyapeeth College of Engin...  
1                   Graduate engineer Trainee at Jio  
2                   Assistant System Engineer at TCS  
3  Student at Bharti Vidyapeeth college of engine...  
4   Assistant Manager(GET) at Reliance jio platforms

In [9]:
data.isnull().sum()

_id               0
certifications    0
education         0
experinces        0
fullName          0
skills            0
title             3
dtype: int64

In [10]:
# data["certifications"]  = data["certifications"].replace({'[{"title":"","from":""}]': ""})

In [11]:
data.sample(10)

_id  \
130  63f1fb9fbef0afbb69a345da   
162  63f202674789131be1b00f5f   
456  63f24005b3ee1a4040d5e673   
376  63f22d9058432de9cc6bb567   
240  63f214fc339c792606803491   
111  63f1e3930666421fed18d442   
514  63f2646a1460f9902e70eca0   
101  63f1e3920666421fed18d406   
572  63f27082a1728d36d79f7baa   
799  63f318e78ea85ff97387823a   

                                        certifications  \
130                           [{"title":"","from":""}]   
162                           [{"title":"","from":""}]   
456                           [{"title":"","from":""}]   
376  [{"title":"Bharati Vidyapeeth College of Engin...   
240  [{"title":"Project Management and Other Tools ...   
111                           [{"title":"","from":""}]   
514  [{"title":"Programming for Everybody (Getting ...   
101  [{"title":"Become a Data Analyst","from":"Link...   
572                           [{"title":"","from":""}]   
799  [{"title":"Neural Networks and Deep Learning",...   

                                             education  \
130  [{"title":"Pesto Tech","degree":"Engineering F...   
162  [{"title":"Bharati Vidyapeeth College of Engin...   
456  [{"title":"Bharati Vidyapeeth College of Engin...   
376  [{"title":"Bharati Vidyapeeth College of Engin...   
240  [{"title":"Bharati Vidyapeeth College of Engin...   
111  [{"title":"Bharati Vidyapeeth College of Engin...   
514  [{"title":"Bharati Vidyapeeth College of Engin...   
101  [{"title":"Bharati Vidyapeeth College of Engin...   
572  [{"title":"Bharati Vidyapeeth College of Engin...   
799  [{"title":"Delhi Technological University","de...   

                                            experinces          fullName  \
130  [{"organization":"Bizpilot · Full-time","title...    Manish Ukirade   
162                                                 []     Bhavik Khatau   
456  [{"organization":"Full-time · 1 yr 4 mosNov 20...   Rutuja Katalkar   
376  [{"organization":"Tembo Global Industries LTD ...    Swapnil Birari   
240  [{"organization":"Teleperformance · Full-time"...    Himanshu Singh   
111  [{"organization":"General Mills India · Full-t...    Sayali Mhaskar   
514  [{"organization":"Jio Platforms Limited (JPL) ...  Prathmesh Jadhav   
101  [{"organization":"NEC Software Solutions (Indi...    Nishchay singh   
572                                                 []       Dhruv Pawar   
799  [{"organization":"Ford Motor Company · Interns...   Siddhant Tiwari   

                                                skills  \
130  ["Web Development","Node.js","AWS Lambda","Rea...   
162  ["Python 3","Java","C (Programming Language)",...   
456                                                 []   
376  ["Engineering","Presentations","Problem Solvin...   
240  ["Project Coordination","Agile   ","SAP Portal...   
111  ["Java","SQL","Business Analysis","Oracle","ET...   
514  ["Graphics","Engineering","Software Design","t...   
101  ["Engineering","English","Project Management",...   
572  ["Programming Languages","C++","Engineering","...   
799  ["Python","Machine Learning","Amazon Web Servi...   

                                                 title  
130                                  Software Engineer  
162                                                 --  
456          Creative and Passionate Interior Designer  
376  Technical Executive at Tembo Global Industries...  
240    IT Change Management Analyst at Teleperformance  
111                    Senior Analyst at General Mills  
514    Mechanical Test Executive at Quess Corp Limited  
101                        Associate Software Engineer  
572           Student at Bharati Vidyapeeth University  
799  M.Tech. (CSE) 2021 | Data Science | Applied AI...

converting strings into list using ast.literal_eval

**Extract Certification Title**
- Extract certification titles from  list of dictionaries 
- Append each title to a certification list
- Return certification list

In [12]:
def extractCertificationTitle(certification):
  eval_object = ast.literal_eval(certification)
  certificationList = []
  for item in eval_object:
    if item["title"]:
      certificationList.append(item["title"])
  return certificationList

Apply extractCertificationTitle() function on each item of certification column

In [13]:
data["certifications"] = data["certifications"].apply(extractCertificationTitle)

In [14]:
data.head()

_id  \
0  63f1e38f0666421fed18d20a   
1  63f1e38f0666421fed18d212   
2  63f1e38f0666421fed18d216   
3  63f1e38f0666421fed18d222   
4  63f1e38f0666421fed18d22a   

                                      certifications  \
0                                                 []   
1                                                 []   
2  [Web Development, Responsive Website Basics: C...   
3                                                 []   
4                                                 []   

                                           education  \
0  [{"title":"Bharati Vidyapeeth College of Engin...   
1  [{"title":"Bharati Vidyapeeth College of Engin...   
2  [{"title":"Bharati Vidyapeeth College of Engin...   
3  [{"title":"Bharati Vidyapeeth College of Engin...   
4  [{"title":"Bharati Vidyapeeth College of Engin...   

                                          experinces              fullName  \
0                                                 []  Pralayika Mandapalli   
1  [{"organization":"Reliance Jio Infocom Limited...       Anshu kumar Jha   
2  [{"organization":"Verzeo · Internship","title"...       Vighnesh Jadhav   
3                                                 []         Siddhi Chavan   
4                                                 []           Snehal Kale   

                                              skills  \
0                                                 []   
1  ["Java","C (Programming Language)","English","...   
2  ["HTML","Cascading Style Sheets (CSS)","Python...   
3  ["Hindi","Cascading Style Sheets (CSS)","HTML5...   
4                                                 []   

                                               title  
0  Student at Bharati Vidyapeeth College of Engin...  
1                   Graduate engineer Trainee at Jio  
2                   Assistant System Engineer at TCS  
3  Student at Bharti Vidyapeeth college of engine...  
4   Assistant Manager(GET) at Reliance jio platforms

In [15]:
def extractSkills(skills):
  eval_obj = ast.literal_eval(skills)
  skillsList = []
  for item in eval_obj:
    print(item)
    skillsList.append(item)
  return skillsList

In [16]:
data["skills"] = data["skills"].apply(extractSkills)

Streaming output truncated to the last 5000 lines.
Python (Programming Language)
Microsoft Office
Programming
Microsoft Excel
3D Computer Aided Design (3D CAD)
Problem Solving
Communication
Microsoft SQL Server
SAP BusinessObjects
SAP Data Services
Database Development
Tableau
SQL
Microsoft Power BI
Database Queries
Engineering
Career Counseling
Sales
Engineering
AutoCAD
Programmable Logic Controller (PLC)
PLC Programming
PLC Allen Bradley
Control Valves
HVAC
HVAC Engineering
HVAC Design
HVAC Controls
Building Automation
Transducers
Sensors
Temperature Sensors
Pressure Sensors
Distributed Control System (DCS)
SCADA
Automation
Control Systems Design
Mechanical Engineering
Control Valves
Programmable Logic Controller (PLC)
PLC Ladder Logic
Process Control
Transducers
HVAC
Microsoft Office
NI LabVIEW
Industrial Automation
Sketching
Portrait Drawing
Power BI
Advanced Excel
Cybersecurity
Networking
Cisco Systems Products
Network Security
Cisco ASA
CCNP Security
Ethical Hacking
Hacking
Cyber

In [17]:
data.head()

_id  \
0  63f1e38f0666421fed18d20a   
1  63f1e38f0666421fed18d212   
2  63f1e38f0666421fed18d216   
3  63f1e38f0666421fed18d222   
4  63f1e38f0666421fed18d22a   

                                      certifications  \
0                                                 []   
1                                                 []   
2  [Web Development, Responsive Website Basics: C...   
3                                                 []   
4                                                 []   

                                           education  \
0  [{"title":"Bharati Vidyapeeth College of Engin...   
1  [{"title":"Bharati Vidyapeeth College of Engin...   
2  [{"title":"Bharati Vidyapeeth College of Engin...   
3  [{"title":"Bharati Vidyapeeth College of Engin...   
4  [{"title":"Bharati Vidyapeeth College of Engin...   

                                          experinces              fullName  \
0                                                 []  Pralayika Mandapalli   
1  [{"organization":"Reliance Jio Infocom Limited...       Anshu kumar Jha   
2  [{"organization":"Verzeo · Internship","title"...       Vighnesh Jadhav   
3                                                 []         Siddhi Chavan   
4                                                 []           Snehal Kale   

                                              skills  \
0                                                 []   
1  [Java, C (Programming Language), English, Elec...   
2  [HTML, Cascading Style Sheets (CSS), Python (P...   
3  [Hindi, Cascading Style Sheets (CSS), HTML5, P...   
4                                                 []   

                                               title  
0  Student at Bharati Vidyapeeth College of Engin...  
1                   Graduate engineer Trainee at Jio  
2                   Assistant System Engineer at TCS  
3  Student at Bharti Vidyapeeth college of engine...  
4   Assistant Manager(GET) at Reliance jio platforms

In [18]:
data["education"].iloc[2]

'[{"title":"Bharati Vidyapeeth College of Engineering, Navi Mumbai","degree":"Bachelor of Engineering - BE, Information Technology","date":"2018 - 2022"},{"title":"Ramnarain Ruia College - Mumbai","degree":"Computer Science","date":"2016 - 2018"},{"title":"R. N. Raut High School","degree":"2011 - 2016","date":""}]'

In [19]:
"Ramnarain Ruia College".count("Bharati Vidyapeeth College of Engineering")

bool(0)

False

In [20]:

def extractEducation(education):
  education_eval = ast.literal_eval(education)
  # print(education_eval)
  degree_list=[]
  for item in education_eval:
    if item['title'].count("Bharati Vidyapeeth College of Engineering"):
      for x in Departments.keys():
        str = item["degree"].lower()
        if str.count(x):
          degree_list.append(Departments[x])
          return Departments[x]

  return "" 


extractEducation(data["education"].iloc[2])


'Information Technology'

In [21]:
data['education'] = data['education'].apply(extractEducation)

In [22]:
data.head(10)

_id  \
0  63f1e38f0666421fed18d20a   
1  63f1e38f0666421fed18d212   
2  63f1e38f0666421fed18d216   
3  63f1e38f0666421fed18d222   
4  63f1e38f0666421fed18d22a   
5  63f1e38f0666421fed18d22e   
6  63f1e38f0666421fed18d232   
7  63f1e38f0666421fed18d23a   
8  63f1e38f0666421fed18d23e   
9  63f1e38f0666421fed18d242   

                                      certifications  \
0                                                 []   
1                                                 []   
2  [Web Development, Responsive Website Basics: C...   
3                                                 []   
4                                                 []   
5                                                 []   
6                                                 []   
7  [MACHINE LEARNING WITH PYTHON, Data Science Us...   
8                 [SQL BASIC, JAVA BASIC, Core Java]   
9         [Computing in Python III: Data Structures]   

                          education  \
0  Electronic and Telecommunication   
1  Electronic and Telecommunication   
2            Information Technology   
3            Information Technology   
4              Computer Engineering   
5  Electronic and Telecommunication   
6              Computer Engineering   
7            Information Technology   
8            Information Technology   
9              Computer Engineering   

                                          experinces              fullName  \
0                                                 []  Pralayika Mandapalli   
1  [{"organization":"Reliance Jio Infocom Limited...       Anshu kumar Jha   
2  [{"organization":"Verzeo · Internship","title"...       Vighnesh Jadhav   
3                                                 []         Siddhi Chavan   
4                                                 []           Snehal Kale   
5                                                 []           Neha Kharat   
6                                                 []           Omkar Suwar   
7  [{"organization":"Fruzi App · Internship","tit...       Vaibhav Mandale   
8  [{"organization":"Wipro Limited · Full-time","...           Omkar Pawar   
9  [{"organization":"Accenture · Full-time","titl...     Mrugakshi Thakare   

                                              skills  \
0                                                 []   
1  [Java, C (Programming Language), English, Elec...   
2  [HTML, Cascading Style Sheets (CSS), Python (P...   
3  [Hindi, Cascading Style Sheets (CSS), HTML5, P...   
4                                                 []   
5                                                 []   
6                                                 []   
7  [Data Science, Machine Learning, Python (Progr...   
8  [Database Management System (DBMS), Java, Web ...   
9  [Adobe Creative Cloud, Figma, HTML, Python (Pr...   

                                               title  
0  Student at Bharati Vidyapeeth College of Engin...  
1                   Graduate engineer Trainee at Jio  
2                   Assistant System Engineer at TCS  
3  Student at Bharti Vidyapeeth college of engine...  
4   Assistant Manager(GET) at Reliance jio platforms  
5                    Student at University of Mumbai  
6  Student at Bharati Vidyapeeth College of Engin...  
7            Assistant Manager (GET) at Reliance JIO  
8                  Project Engineer at Wipro Limited  
9           Associate Software Engineer at Accenture

In [23]:
data = data.rename(columns = {'experinces':'experiences'})
data.head()

_id  \
0  63f1e38f0666421fed18d20a   
1  63f1e38f0666421fed18d212   
2  63f1e38f0666421fed18d216   
3  63f1e38f0666421fed18d222   
4  63f1e38f0666421fed18d22a   

                                      certifications  \
0                                                 []   
1                                                 []   
2  [Web Development, Responsive Website Basics: C...   
3                                                 []   
4                                                 []   

                          education  \
0  Electronic and Telecommunication   
1  Electronic and Telecommunication   
2            Information Technology   
3            Information Technology   
4              Computer Engineering   

                                         experiences              fullName  \
0                                                 []  Pralayika Mandapalli   
1  [{"organization":"Reliance Jio Infocom Limited...       Anshu kumar Jha   
2  [{"organization":"Verzeo · Internship","title"...       Vighnesh Jadhav   
3                                                 []         Siddhi Chavan   
4                                                 []           Snehal Kale   

                                              skills  \
0                                                 []   
1  [Java, C (Programming Language), English, Elec...   
2  [HTML, Cascading Style Sheets (CSS), Python (P...   
3  [Hindi, Cascading Style Sheets (CSS), HTML5, P...   
4                                                 []   

                                               title  
0  Student at Bharati Vidyapeeth College of Engin...  
1                   Graduate engineer Trainee at Jio  
2                   Assistant System Engineer at TCS  
3  Student at Bharti Vidyapeeth college of engine...  
4   Assistant Manager(GET) at Reliance jio platforms

In [24]:
type(data['experiences'].iloc[2])


str

In [25]:
def extractExp(exp):
  exp_eval = ast.literal_eval(exp)
  exp_list = []
  for item in exp_eval:
    exp_list.append(item["organization"])
    exp_list.append(item["title"])
  return exp_list

extractExp(data['experiences'].iloc[2])
    

['Verzeo · Internship', 'Web Development']

In [26]:
data['experiences'] = data['experiences'].apply(extractExp)


In [27]:
data.sample(10)


_id  \
361  63f22bc6e18d4e21e2819701   
130  63f1fb9fbef0afbb69a345da   
661  63f2745fa1728d36d79f7d06   
177  63f2084f26aec911e5a0d4aa   
449  63f23f32b3ee1a4040d5e647   
659  63f27448a1728d36d79f7cfe   
124  63f1e3930666421fed18d482   
650  63f273fba1728d36d79f7ce2   
256  63f21773b018fbc2f8045b34   
472  63f24393f3ffa20e1090954a   

                                        certifications  \
361  [ISO/TS Internal Auditor, Lean Six Sigma Green...   
130                                                 []   
661                                                 []   
177                                                 []   
449                                                 []   
659  [Building a Business Presence With Facebook Ma...   
124                                                 []   
650                                                 []   
256  [Foundations of Operationalizing MITRE ATT&CK,...   
472                                                 []   

                            education  \
361            Mechanical Engineering   
130            Information Technology   
661              Chemical Engineering   
177              Computer Engineering   
449                                     
659            Mechanical Engineering   
124              Chemical Engineering   
650              Chemical Engineering   
256  Electronic and Telecommunication   
472              Computer Engineering   

                                           experiences        fullName  \
361  [FIRMENICH AROMATICS PRODUCTION (INDIA) PRIVAT...     Mrinal Rane   
130  [Bizpilot · Full-time, Software Engineer, Rayk...  Manish Ukirade   
661  [Fengyuan India Pvt. Ltd · Full-time, Internat...   Akash Dhainje   
177        [Lionbridge · Full-time, Software Engineer]   Diksha Chalke   
449                                                 []      Neha Patil   
659                                                 []   Saurabh Patil   
124  [Rashtriya Chemicals & Fertilizers Limited · I...    Nihal undire   
650  [Indian Institute of Chemical Engineers · Inte...       Simran K.   
256  [Kotak Mahindra Bank · Full-time, Manager - IT...   Siddhesh Vast   
472                                                 []    Ritesh Hiray   

                                                skills  \
361  [Microsoft Excel, Production Planning, Schedul...   
130  [Web Development, Node.js, AWS Lambda, React.j...   
661  [Engineering, English, Communication, Analytic...   
177  [Microsoft Excel, Microsoft Office, Management...   
449  [SQL, Java, Python (Programming Language), Jav...   
659  [SOLIDWORKS, Microsoft Excel, Microsoft Word, ...   
124  [English, Research, Marketing, Training, Commu...   
650                                                 []   
256  [Deception, Security Information and Event Man...   
472  [Education, Management, Communication, Project...   

                                                 title  
361  Material Planner | Supply Chain Management |  ...  
130                                  Software Engineer  
661  Student at Bharati Vidyapeeth College of Engin...  
177       Software Engineer at Lionbridge Technologies  
449  Student at Bharati Vidyapeeth College of Engin...  
659                       Student at Bharti vidyappeth  
124                                  chemical engineer  
650                       Chemical Engineering Student  
256                         Information Security | CEH  
472  Student at Bharati Vidyapeeth College of Engin...

In [28]:
data["experiences"].iloc[613]

['Zeeco India Pvt Ltd on contract with Canaan Engineering Pvt Ltd · Full-time',
 'Senior Project Engineer ',
 'Canaan Engineering Pvt Ltd · Full-time',
 'Production Engineer']

In [29]:
data.head(100)

_id  \
0   63f1e38f0666421fed18d20a   
1   63f1e38f0666421fed18d212   
2   63f1e38f0666421fed18d216   
3   63f1e38f0666421fed18d222   
4   63f1e38f0666421fed18d22a   
..                       ...   
95  63f1e3920666421fed18d3e2   
96  63f1e3920666421fed18d3e6   
97  63f1e3920666421fed18d3ee   
98  63f1e3920666421fed18d3f2   
99  63f1e3920666421fed18d3f6   

                                       certifications  \
0                                                  []   
1                                                  []   
2   [Web Development, Responsive Website Basics: C...   
3                                                  []   
4                                                  []   
..                                                ...   
95                                                 []   
96                                                 []   
97                                                 []   
98  [AWS Fundamentals Specialization, Google IT Au...   
99                                                 []   

                           education  \
0   Electronic and Telecommunication   
1   Electronic and Telecommunication   
2             Information Technology   
3             Information Technology   
4               Computer Engineering   
..                               ...   
95              Chemical Engineering   
96              Chemical Engineering   
97            Information Technology   
98            Information Technology   
99  Electronic and Telecommunication   

                                          experiences              fullName  \
0                                                  []  Pralayika Mandapalli   
1   [Reliance Jio Infocom Limited, Assistant Manager]       Anshu kumar Jha   
2              [Verzeo · Internship, Web Development]       Vighnesh Jadhav   
3                                                  []         Siddhi Chavan   
4                                                  []           Snehal Kale   
..                                                ...                   ...   
95  [Full-time · 1 yr 8 mosApr 2022 - Feb 2023 · 1...          Akshra Patil   
96  [Rashtriya Chemicals & Fertilizers Limited · I...         Raj Katrapwar   
97                               [Capgemini, Analyst]         ajay bhandare   
98  [Full-time · 1 yr 9 mosJul 2022 - Present · 8 ...       ANKIT SINGHANIA   
99                      [Capgemini, Software Analyst]            Anuja Raut   

                                               skills  \
0                                                  []   
1   [Java, C (Programming Language), English, Elec...   
2   [HTML, Cascading Style Sheets (CSS), Python (P...   
3   [Hindi, Cascading Style Sheets (CSS), HTML5, P...   
4                                                  []   
..                                                ...   
95  [Petrochemical, Process Engineering, Procureme...   
96                                                 []   
97                                [power bi, Tableau]   
98  [Microsoft Office, Data Structures, C++, Event...   
99  [Spanish, HTML, Cascading Style Sheets (CSS), ...   

                                                title  
0   Student at Bharati Vidyapeeth College of Engin...  
1                    Graduate engineer Trainee at Jio  
2                    Assistant System Engineer at TCS  
3   Student at Bharti Vidyapeeth college of engine...  
4    Assistant Manager(GET) at Reliance jio platforms  
..                                                ...  
95                                   Process Engineer  
96                                  Chemical Engineer  
97                               Analyst At Capgemini  
98                                  Software Engineer  
99                               Analyst at Capgemini  

[100 rows x 7 columns]

In [30]:
len(list(data["experiences"].iloc))

835

In [31]:
data["experiences"].iloc[98]

['Full-time · 1 yr 9 mosJul 2022 - Present · 8 mosJun 2021 - Aug 2022 · 1 yr 3 mos',
 'GEP WorldwideSoftware EngineerJul 2022 - Present · 8 mosIndiaAssociate Software EngineerJun 2021 - Aug 2022 · 1 yr 3 mosThane, Maharashtra, India',
 'Bharati Vidyapeeth Information Technology Department · Full-time',
 'Vice President',
 'Avotrix · Internship',
 'IOT Developer',
 'Sigmaflux · Internship',
 'Web Developer   ']

In [32]:
def handleExperienceTimeline(experiencesColumn):
  count = 0
  idList = []
  for li in range(0,len(list(experiencesColumn))):
    experienceList = experiencesColumn[li]
    for i in range(len(experienceList)):
      if i%2 != 0 and experienceList[i].count(" mos"):
        # print("Experience:",experienceList[i])
        count += 1
        idList.append(li)

        break
  print(count)
  return idList

def strToList(value):
  if type(value) == str:
   return ast.literal_eval(value)
  return value





In [33]:
index_list = handleExperienceTimeline(data["experiences"].iloc)
# print(index_list)
mask = data.index.isin(index_list)
data.loc[mask,"experiences"] = ""
data["experiences"]  = data["experiences"].replace({'': "[]"})


137


In [34]:
data["experiences"] = data["experiences"].apply(strToList)

In [35]:
data['experiences'].sample(10)

321                            [BSNL LTD, Summer Intern]
379    [Velocis Systems Private Limited · Full-time, ...
454                                                   []
682                                                   []
217    [Rashtriya Chemical & Fertilizer Limited. Chem...
179                                                   []
118                                                   []
165    [Intellect Design Arena Ltd · Full-time, Assoc...
130                                                   []
825    [Tata Consultancy Services · Full-time, Assist...
Name: experiences, dtype: object

In [36]:
type(data["experiences"].iloc[11])

list

In [37]:
data["education"] = data["education"].replace("","NA")

In [38]:
data

_id  \
0    63f1e38f0666421fed18d20a   
1    63f1e38f0666421fed18d212   
2    63f1e38f0666421fed18d216   
3    63f1e38f0666421fed18d222   
4    63f1e38f0666421fed18d22a   
..                        ...   
830  63f33e5898a92797f4b1d025   
831  63f33e6d98a92797f4b1d031   
832  63f33e7e98a92797f4b1d039   
833  63f33e8e98a92797f4b1d041   
834  63f33e9898a92797f4b1d045   

                                        certifications  \
0                                                   []   
1                                                   []   
2    [Web Development, Responsive Website Basics: C...   
3                                                   []   
4                                                   []   
..                                                 ...   
830                                                 []   
831                                                 []   
832  [Data Visualization Using Tableau, Introductio...   
833                                                 []   
834                                                 []   

                            education  \
0    Electronic and Telecommunication   
1    Electronic and Telecommunication   
2              Information Technology   
3              Information Technology   
4                Computer Engineering   
..                                ...   
830            Mechanical Engineering   
831            Mechanical Engineering   
832              Computer Engineering   
833              Computer Engineering   
834              Chemical Engineering   

                                           experiences              fullName  \
0                                                   []  Pralayika Mandapalli   
1    [Reliance Jio Infocom Limited, Assistant Manager]       Anshu kumar Jha   
2               [Verzeo · Internship, Web Development]       Vighnesh Jadhav   
3                                                   []         Siddhi Chavan   
4                                                   []           Snehal Kale   
..                                                 ...                   ...   
830  [Teleperformance, Customer Service Representat...       Zubaish Mallick   
831  [Ascent Total Solution Pvt. Ltd. · Apprentices...          Nimish Patil   
832                                                 []         Vishwa Jagtap   
833  [Freelancer.com · Self-employed, Game Develope...          Owais Shaikh   
834  [Full-time · 2 yrs 1 moFeb 2022 - Present · 1 ...           Nigil Mohan   

                                                skills  \
0                                                   []   
1    [Java, C (Programming Language), English, Elec...   
2    [HTML, Cascading Style Sheets (CSS), Python (P...   
3    [Hindi, Cascading Style Sheets (CSS), HTML5, P...   
4                                                   []   
..                                                 ...   
830  [Microsoft PowerPoint, Critical Thinking, Prob...   
831  [Engineering, Project Management, Design, Micr...   
832  [Database Management System (DBMS), Microsoft ...   
833  [Game Development, Game Design, c#, c++, JavaS...   
834  [Chemical Engineering, Process Engineering, PR...   

                                                 title  
0    Student at Bharati Vidyapeeth College of Engin...  
1                     Graduate engineer Trainee at Jio  
2                     Assistant System Engineer at TCS  
3    Student at Bharti Vidyapeeth college of engine...  
4     Assistant Manager(GET) at Reliance jio platforms  
..                                                 ...  
830                                                 --  
831                                   Project Engineer  
832  Senior System Engineer at Infosys | Reporting ...  
833                                         Freelancer  
834                       Process Engineer I at Worley  

[835 rows x 7 columns]

In [39]:
def removeSpace(words):
  words = str(words).split()
  joinedWords = "".join(words)
  return joinedWords




In [40]:
data["education"] = data["education"].apply(removeSpace)
# data["fullName"] = data["fullName"].apply(removeSpace)
data["title"] = data["title"].apply(removeSpace)

data.sample(10)

_id  \
162  63f202674789131be1b00f5f   
128  63f1e3940666421fed18d49e   
143  63f1fddc17915243e6cfe435   
473  63f243a4f3ffa20e10909552   
451  63f23f84b3ee1a4040d5e653   
230  63f2142b4d27ad4a7393f153   
560  63f26de45bdf2b930af49e9a   
255  63f21755b018fbc2f8045b30   
105  63f1e3930666421fed18d41a   
312  63f228d38d77e9e457495ca8   

                                        certifications  \
162                                                 []   
128                                                 []   
143                                                 []   
473           [Basics of IPR, Entrepreneurship Course]   
451                                                 []   
230                                                 []   
560                                                 []   
255  [ICSI | CNSS Certified Network Security Specia...   
105  [SQL  (Intermediate), java (Basic), AI For Eve...   
312                                                 []   

                          education  \
162           InformationTechnology   
128             ComputerEngineering   
143           InformationTechnology   
473             ChemicalEngineering   
451                              NA   
230  ElectronicandTelecommunication   
560             ComputerEngineering   
255             ComputerEngineering   
105           InformationTechnology   
312             ComputerEngineering   

                                           experiences            fullName  \
162                                                 []       Bhavik Khatau   
128                                                 []           Rutika B.   
143                                                 []          Ajay Lohar   
473                                                 []     Priscilla Agnel   
451  [Optimal Business Solutions, LLC · Full-time, ...  Shivanjali Sangale   
230  [Apmosys technologies Pvt Ltd · Full-time, Sof...    PRIYANKA SARGADE   
560  [Yodaplus · Full-time, Software Engineer, PNT ...   Pushpak Pachpande   
255                                                 []        Sumit Pandey   
105  [Wipro · Full-time, Project Engineer, Cloud Co...        Bhikan Patil   
312  [Bharati Vidyapeeths College of Engineering Se...        sanjay kadam   

                                                skills  \
162  [Python 3, Java, C (Programming Language), CSS...   
128                                                 []   
143  [Python (Programming Language), HTML, Cascadin...   
473  [Process Flow Diagrams, Engineering, Line trac...   
451                                                 []   
230  [Dynatrace, Linux, AppDynamics, Python (Progra...   
560  [Coding Experience, C (Programming Language), ...   
255  [Mentoring, Leadership, Data Structures, Algor...   
105  [ASP.NET, Artificial Intelligence (AI), CMOD, ...   
312  [IT Operations, Web Development, NFV and SDN, ...   

                                                 title  
162                                                 --  
128                                   SoftwareEngineer  
143  StudentatBharatiVidyapeethCollegeofEngineering...  
473  PostGraduateStudentatInstituteofChemicalTechno...  
451                                           Engineer  
230  Passionateaboutengineeringlearningforfuturetec...  
560                         CurrentlyworkinginYodaplus  
255  SoftwareEngineer@TCSDigital|CompetitiveProgrammer  
105                      ProjectEngineeratWiproLimited  
312  AssistantProfessoratBharatiVidyapeethsCollegeo...

In [41]:
data["title"].unique()

array(['StudentatBharatiVidyapeethCollegeofEngineering,NaviMumbai',
       'GraduateengineerTraineeatJio', 'AssistantSystemEngineeratTCS',
       'StudentatBhartiVidyapeethcollegeofengineering',
       'AssistantManager(GET)atReliancejioplatforms',
       'StudentatUniversityofMumbai',
       'AssistantManager(GET)atRelianceJIO',
       'ProjectEngineeratWiproLimited',
       'AssociateSoftwareEngineeratAccenture',
       'ApplicationDevelopmentAnalyst',
       'StudentatBhartiVidyapeethCollegeofEngineering',
       "UniversityofMumbai'23",
       'SoftwareEngineeratAccenture(ReactJs|typescript|node.js)',
       'AssociateSoftwareEngineer', 'SoftwareEngineer',
       'AssociateSoftwareEngineer@GEP', 'GraduateEngineerTrainee@Vertiv',
       'SeniorSoftwareEngineeratCapgemini', 'SoftwareEngineeratVedantu',
       'SoftwareDeveloperatAmdocs',
       'StudentatBharatiVidyapeethCollegeofEngineering',
       'SDE-Frontend@JIO-Jiomeet|Angular',
       'SoftwareEngineeratGEPWorldwide', 'System

In [42]:
def listRemoveSpace(itemList):
  wordContainer = []
  for item in itemList:
    wordContainer.append(removeSpace(item).split("·")[0])
  return wordContainer



In [43]:
data["certifications"]= data["certifications"].apply(listRemoveSpace)
data["skills"]= data["skills"].apply(listRemoveSpace)
data["experiences"]= data["experiences"].apply(listRemoveSpace)

In [44]:
data.head(10)

_id  \
0  63f1e38f0666421fed18d20a   
1  63f1e38f0666421fed18d212   
2  63f1e38f0666421fed18d216   
3  63f1e38f0666421fed18d222   
4  63f1e38f0666421fed18d22a   
5  63f1e38f0666421fed18d22e   
6  63f1e38f0666421fed18d232   
7  63f1e38f0666421fed18d23a   
8  63f1e38f0666421fed18d23e   
9  63f1e38f0666421fed18d242   

                                      certifications  \
0                                                 []   
1                                                 []   
2  [WebDevelopment, ResponsiveWebsiteBasics:Codew...   
3                                                 []   
4                                                 []   
5                                                 []   
6                                                 []   
7  [MACHINELEARNINGWITHPYTHON, DataScienceUsingPy...   
8                    [SQLBASIC, JAVABASIC, CoreJava]   
9              [ComputinginPythonIII:DataStructures]   

                        education  \
0  ElectronicandTelecommunication   
1  ElectronicandTelecommunication   
2           InformationTechnology   
3           InformationTechnology   
4             ComputerEngineering   
5  ElectronicandTelecommunication   
6             ComputerEngineering   
7           InformationTechnology   
8           InformationTechnology   
9             ComputerEngineering   

                                         experiences              fullName  \
0                                                 []  Pralayika Mandapalli   
1      [RelianceJioInfocomLimited, AssistantManager]       Anshu kumar Jha   
2                           [Verzeo, WebDevelopment]       Vighnesh Jadhav   
3                                                 []         Siddhi Chavan   
4                                                 []           Snehal Kale   
5                                                 []           Neha Kharat   
6                                                 []           Omkar Suwar   
7  [FruziApp, DataScienceIntern, TheSparksFoundat...       Vaibhav Mandale   
8  [WiproLimited, ProjectEngineer, TheSparksFound...           Omkar Pawar   
9  [Accenture, AssociateSoftwareEngineer, Success...     Mrugakshi Thakare   

                                              skills  \
0                                                 []   
1  [Java, C(ProgrammingLanguage), English, Electr...   
2  [HTML, CascadingStyleSheets(CSS), Python(Progr...   
3  [Hindi, CascadingStyleSheets(CSS), HTML5, Prob...   
4                                                 []   
5                                                 []   
6                                                 []   
7  [DataScience, MachineLearning, Python(Programm...   
8  [DatabaseManagementSystem(DBMS), Java, WebDeve...   
9  [AdobeCreativeCloud, Figma, HTML, Python(Progr...   

                                               title  
0  StudentatBharatiVidyapeethCollegeofEngineering...  
1                       GraduateengineerTraineeatJio  
2                       AssistantSystemEngineeratTCS  
3      StudentatBhartiVidyapeethcollegeofengineering  
4        AssistantManager(GET)atReliancejioplatforms  
5                        StudentatUniversityofMumbai  
6  StudentatBharatiVidyapeethCollegeofEngineering...  
7                 AssistantManager(GET)atRelianceJIO  
8                      ProjectEngineeratWiproLimited  
9               AssociateSoftwareEngineeratAccenture

In [45]:
def convertStrToList(value):
  if type(value) != list:
    return [value]
  return value

In [46]:
convertStrToList("ElectronicandTelecommunication")

['ElectronicandTelecommunication']

In [47]:
data["education"] = data["education"].apply(convertStrToList)
data["title"] = data["title"].apply(convertStrToList)

data.head()


_id  \
0  63f1e38f0666421fed18d20a   
1  63f1e38f0666421fed18d212   
2  63f1e38f0666421fed18d216   
3  63f1e38f0666421fed18d222   
4  63f1e38f0666421fed18d22a   

                                      certifications  \
0                                                 []   
1                                                 []   
2  [WebDevelopment, ResponsiveWebsiteBasics:Codew...   
3                                                 []   
4                                                 []   

                          education  \
0  [ElectronicandTelecommunication]   
1  [ElectronicandTelecommunication]   
2           [InformationTechnology]   
3           [InformationTechnology]   
4             [ComputerEngineering]   

                                     experiences              fullName  \
0                                             []  Pralayika Mandapalli   
1  [RelianceJioInfocomLimited, AssistantManager]       Anshu kumar Jha   
2                       [Verzeo, WebDevelopment]       Vighnesh Jadhav   
3                                             []         Siddhi Chavan   
4                                             []           Snehal Kale   

                                              skills  \
0                                                 []   
1  [Java, C(ProgrammingLanguage), English, Electr...   
2  [HTML, CascadingStyleSheets(CSS), Python(Progr...   
3  [Hindi, CascadingStyleSheets(CSS), HTML5, Prob...   
4                                                 []   

                                               title  
0  [StudentatBharatiVidyapeethCollegeofEngineerin...  
1                     [GraduateengineerTraineeatJio]  
2                     [AssistantSystemEngineeratTCS]  
3    [StudentatBhartiVidyapeethcollegeofengineering]  
4      [AssistantManager(GET)atReliancejioplatforms]

## **creating tags by concatenating education, experiences,certifications,title, skills**

In [48]:
data["tags"] = data["education"] + data["experiences"] + data["certifications"] + data["skills"] + data["title"]
list(data["tags"].iloc)

[['ElectronicandTelecommunication',
  'StudentatBharatiVidyapeethCollegeofEngineering,NaviMumbai'],
 ['ElectronicandTelecommunication',
  'RelianceJioInfocomLimited',
  'AssistantManager',
  'Java',
  'C(ProgrammingLanguage)',
  'English',
  'ElectronicEngineering',
  'Engineering',
  'Electronics',
  'PressureSituations',
  'startupenthusiasts',
  'GraduateengineerTraineeatJio'],
 ['InformationTechnology',
  'Verzeo',
  'WebDevelopment',
  'WebDevelopment',
  'ResponsiveWebsiteBasics:CodewithHTML,CSS,andJavaScript',
  'ProgrammingforEverybody(GettingStartedwithPython)',
  'PythonDataStructures',
  'AWSCertifiedCloudPractitioner',
  'HTML',
  'CascadingStyleSheets(CSS)',
  'Python(ProgrammingLanguage)',
  'Front-endDevelopment',
  'Django',
  'Bootstrap',
  'C(ProgrammingLanguage)',
  'MicrosoftExcel',
  'MicrosoftOffice',
  'Java',
  'MicrosoftWord',
  'MicrosoftPowerPoint',
  'SQL',
  'AssistantSystemEngineeratTCS'],
 ['InformationTechnology',
  'Hindi',
  'CascadingStyleSheets(CSS)'

In [49]:
def listToStringLower(tagsList):
  return " ".join(tagsList).lower()

In [50]:
data["tags"] = data["tags"].apply(listToStringLower)

In [51]:
df = data.drop(['education','experiences','certifications','title','skills'], axis=1)
df.head()

_id              fullName  \
0  63f1e38f0666421fed18d20a  Pralayika Mandapalli   
1  63f1e38f0666421fed18d212       Anshu kumar Jha   
2  63f1e38f0666421fed18d216       Vighnesh Jadhav   
3  63f1e38f0666421fed18d222         Siddhi Chavan   
4  63f1e38f0666421fed18d22a           Snehal Kale   

                                                tags  
0  electronicandtelecommunication studentatbharat...  
1  electronicandtelecommunication reliancejioinfo...  
2  informationtechnology verzeo webdevelopment we...  
3  informationtechnology hindi cascadingstyleshee...  
4  computerengineering assistantmanager(get)atrel...

# **Stemming**

In [52]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [53]:
def stem(text):
  y = []
  for i in text.split():
    y.append(ps.stem(i))
  return " ".join(y)

In [54]:
df["tags"] = df["tags"].apply(stem)

In [55]:
df

_id              fullName  \
0    63f1e38f0666421fed18d20a  Pralayika Mandapalli   
1    63f1e38f0666421fed18d212       Anshu kumar Jha   
2    63f1e38f0666421fed18d216       Vighnesh Jadhav   
3    63f1e38f0666421fed18d222         Siddhi Chavan   
4    63f1e38f0666421fed18d22a           Snehal Kale   
..                        ...                   ...   
830  63f33e5898a92797f4b1d025       Zubaish Mallick   
831  63f33e6d98a92797f4b1d031          Nimish Patil   
832  63f33e7e98a92797f4b1d039         Vishwa Jagtap   
833  63f33e8e98a92797f4b1d041          Owais Shaikh   
834  63f33e9898a92797f4b1d045           Nigil Mohan   

                                                  tags  
0    electronicandtelecommun studentatbharatividyap...  
1    electronicandtelecommun reliancejioinfocomlimi...  
2    informationtechnolog verzeo webdevelop webdeve...  
3    informationtechnolog hindi cascadingstylesheet...  
4    computerengin assistantmanager(get)atreliancej...  
..                                                 ...  
830  mechanicalengin teleperform customerservicerep...  
831  mechanicalengin ascenttotalsolutionpvt.ltd. pr...  
832  computerengin datavisualizationusingtableau in...  
833  computerengin freelancer.com gamedevelop kickb...  
834  chemicalengin full-tim worleyprocessengineerif...  

[835 rows x 3 columns]

In [56]:
list(df["tags"].iloc)

['electronicandtelecommun studentatbharatividyapeethcollegeofengineering,navimumbai',
 'electronicandtelecommun reliancejioinfocomlimit assistantmanag java c(programminglanguage) english electronicengin engin electron pressuresitu startupenthusiast graduateengineertraineeatjio',
 'informationtechnolog verzeo webdevelop webdevelop responsivewebsitebasics:codewithhtml,css,andjavascript programmingforeverybody(gettingstartedwithpython) pythondatastructur awscertifiedcloudpractition html cascadingstylesheets(css) python(programminglanguage) front-enddevelop django bootstrap c(programminglanguage) microsoftexcel microsoftoffic java microsoftword microsoftpowerpoint sql assistantsystemengineerattc',
 'informationtechnolog hindi cascadingstylesheets(css) html5 problemsolv java python(programminglanguage) microsoftexcel english studentatbhartividyapeethcollegeofengin',
 'computerengin assistantmanager(get)atreliancejioplatform',
 'electronicandtelecommun studentatuniversityofmumbai',
 'compute

# Feature Extraction

*Stopwords* are a common feature in natural language processing and are frequently used in text analysis tasks. 

Stopwords are words that are commonly used in a language, but they are often ignored when analyzing text because they do not contain significant meaning or value.

example of stop words in english
```
stop_words = ['a', 'an', 'and', 'are', 'as', 'at', 'be', 'by', 'for', 'from', 'has', 'he', 'in', 'is', 'it', 'its', 'of', 'on', 'that', 'the', 'to', 'was', 'were', 'with']

```



In [57]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words="english")


**CountVectorizer** is a popular method for vectorizing text data, which converts a collection of text documents to a matrix of token counts. 



The fit_transform() method of CountVectorizer performs two essential operations:

- **fitting:** it fits the CountVectorizer on the input text data to build a vocabulary, which is a list of all the unique words (tokens) in the text corpus. It also assigns an index to each token in the vocabulary.

- **transforming:** it transforms the input text data into a matrix of token counts, where each row represents a document, and each column represents a unique token in the vocabulary. The matrix stores the frequency of each token in each document.

In [58]:
vectors = cv.fit_transform(df["tags"]).toarray()


In [59]:
list(vectors)

[array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0,

In [60]:
vectors.shape

(835, 5000)

# Cosine Similarity

In [61]:
from sklearn.metrics.pairwise import cosine_similarity

  - The **cosine_similarity()** function calculates the cosine similarity between pairs of vectors in the input matrix vectors. 
  - Cosine similarity is a metric that measures the cosine of the angle between two non-zero vectors in an n-dimensional space. 

  - It ranges between -1 and 1, where 1 indicates that the vectors are identical, and 0 indicates that they are orthogonal (i.e., perpendicular), and -1 indicates that they are diametrically opposed.

  - The output of cosine_similarity(vectors) is a symmetric matrix of shape (n_samples, n_samples), where n_samples is the number of vectors in vectors.

  - The diagonal elements of the matrix are all 1, indicating that each vector is perfectly similar to itself. 

  - The off-diagonal elements represent the cosine similarity between pairs of vectors, where higher values indicate greater similarity.

In [62]:
similarity = cosine_similarity(vectors)

In [63]:
similarity.shape

(835, 835)

In [64]:
similarity

array([[1.        , 0.17407766, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.17407766, 1.        , 0.15512631, ..., 0.        , 0.        ,
        0.13159034],
       [0.        , 0.15512631, 1.        , ..., 0.046676  , 0.        ,
        0.1871203 ],
       ...,
       [0.        , 0.        , 0.046676  , ..., 1.        , 0.08164966,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.08164966, 1.        ,
        0.        ],
       [0.        , 0.13159034, 0.1871203 , ..., 0.        , 0.        ,
        1.        ]])

In [65]:
similarity[0]

array([1.        , 0.17407766, 0.        , 0.        , 0.        ,
       0.40824829, 0.66666667, 0.        , 0.        , 0.        ,
       0.66666667, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.18257419, 0.11547005, 0.        , 0.11111111,
       0.16012815, 0.12309149, 0.        , 0.38490018, 0.16666667,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.23570226, 0.27050089, 0.12909944,
       0.        , 0.0860663 , 0.11111111, 0.        , 0.        ,
       0.        , 0.16012815, 0.        , 0.        , 0.        ,
       0.57735027, 0.        , 0.        , 0.        , 0.10910895,
       0.        , 0.43643578, 0.19245009, 0.        , 0.14433757,
       0.        , 0.        , 0.        , 0.16666667, 0.        ,
       0.12909944, 0.        , 0.        , 0.        , 0.0949158 ,
       0.        , 0.        , 0.25819889, 0.        , 0.23094011,
       0.        , 0.66666667, 0.        , 0.        , 0.13245

Enumeration
- Enumeration is the process of assigning a unique identifier (usually a number or index) to each item in a collection or sequence. 

- Enumeration is often used to keep track of the position of an item in a list or array, to facilitate searching, sorting, or filtering operations




In [66]:
from IPython.display import HTML
HTML('<iframe width="698" height="393" src="https://www.youtube.com/embed/kGnYc_h1geM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>')

/usr/local/lib/python3.9/dist-packages/IPython/core/display.py:701: UserWarning: Consider using IPython.display.IFrame instead
  warnings.warn("Consider using IPython.display.IFrame instead")


In [67]:
x = sorted(enumerate(["a","j","b","d","w"]),key=lambda x:x[1])
print(x)


[(0, 'a'), (2, 'b'), (3, 'd'), (1, 'j'), (4, 'w')]


Similarity Matrix for first index element(Profile)

In [68]:
list(enumerate(similarity[0]))[0:6]

[(0, 1.0000000000000002),
 (1, 0.17407765595569785),
 (2, 0.0),
 (3, 0.0),
 (4, 0.0),
 (5, 0.408248290463863)]

# Top 5 similar elements(Profiles) to selected element(Profile)


*   Sort enumerated list in reverse order. So that elements that have higher similarities will come at the top
*   Access access first 5 elements which will be similar to selected elements


**Sorting**
- **sorted()** function is used to sort collections like list, tupple, etc.
- When Revered flag is set True then collection is sorted in reverse order


**Example:**


```
ls = [4,52,2,6,8,23]
print("Normal:",sorted(ls))
print("Reversed:",sorted(ls,reverse=True))
```

**Output**


```
Normal: [2, 4, 6, 8, 23, 52]
Reversed: [52, 23, 8, 6, 4, 2]
```





## Sort elements based on values of their similarity

After enumaration list of similarity for selected profile is like


```
[(0, 1.0000000000000002),
 (1, 0.17407765595569785),
 (2, 0.0),
 (3, 0.0),
 (4, 0.0)]
```

each element in list is a tupple **(index,similarity)** with index 0,1 respectively 

now we want to sort list based on similarity so we will use similarity as key for sorting


In [69]:
similarProfiles = list(enumerate(similarity[234]))
sortedSimilarProfiles = sorted(similarProfiles,reverse=True,key = lambda x:x[1])
top5SimilarProfiles = sortedSimilarProfiles[0:6]
top5SimilarProfiles



[(234, 1.0),
 (207, 0.6269355057278586),
 (472, 0.42183074386605374),
 (143, 0.3805211953235953),
 (160, 0.3796283011826483),
 (263, 0.3796283011826483)]

In [70]:
dataDict = data.to_dict(orient="record")


<ipython-input-70-0bac500484c4>:1: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  dataDict = data.to_dict(orient="record")


In [ ]:

for i in top5SimilarProfiles:
  print()
  for key in dataDict[i[0]]:
    print(f"{key}: {dataDict[i[0]][key]}")
  print("-"*100)

# Recommend Function

In [79]:
def recommendProfile(profileIndex):
  similarProfiles = list(enumerate(similarity[profileIndex]))
  sortedSimilarProfiles = sorted(similarProfiles,reverse=True,key = lambda x:x[1])
  top5SimilarProfiles = sortedSimilarProfiles[0:6]
  top5SimilarProfiles
  for i in top5SimilarProfiles:
    print()
    for key in dataDict[i[0]]:
      print(f"{key}: {dataDict[i[0]][key]}")
    print("-"*100)

In [80]:
def recommendProfileById(id):
  index = df[df["_id"]=="63f1e38f0666421fed18d222"].index[0]
  return recommendProfile(index)

In [ ]:
recommendProfileById("63f21738b018fbc2f8045b2c")

In [81]:
import pickle


In [82]:
with open("df.pkl", "wb") as df_pkl:
  pickle.dump(df, df_pkl)

In [83]:
with open("similarity.pkl", "wb") as similarity_pkl:
  pickle.dump(similarity, similarity_pkl)

In [96]:
with open("dataDict.pkl", "wb") as dataDict_pkl:
  pickle.dump(dataDict, dataDict_pkl)

In [97]:
class AlumniRecommendationModel:
  def __init__(self, df_pkl, dataDict_pkl ,similarity_pkl):
    self.df = pickle.load(df_pkl)
    self.similarity = pickle.load(similarity_pkl)
    self.dataDict = pickle.load(dataDict_pkl)

  def recommendProfile(self, profileIndex):
    similarProfiles = list(enumerate(self.similarity[profileIndex]))
    sortedSimilarProfiles = sorted(similarProfiles,reverse=True,key = lambda x:x[1])
    top5SimilarProfiles = sortedSimilarProfiles[0:6]
    top5SimilarProfiles
    for i in top5SimilarProfiles:
      print()
      for key in self.dataDict[i[0]]:
        print(f"{key}: {self.dataDict[i[0]][key]}")
      print("-"*100)

  def recommendProfileById(self,id):
    index = self.df[self.df["_id"]=="63f1e38f0666421fed18d222"].index[0]
    return self.recommendProfile(index)

In [100]:
alumniRecommendationModel = AlumniRecommendationModel(open("df.pkl","rb"),open("dataDict.pkl","rb"),open("similarity.pkl","rb"))

In [ ]:
alumniRecommendationModel.recommendProfileById("63f21738b018fbc2f8045b2c")